- package-lock.json
- package.json
- src/containers.tsx
- src/index.tsx
- src/reducers.tsx
> Upgrade dependencies

- .prettierrc
- package-lock.json
- package.json
- src/actions.tsx
- src/components/Arronax.tsx
- src/components/DataPanel.tsx
- src/components/ExpandableGrid.tsx
- src/components/ExpandableGridRow.tsx
- src/components/FilterPanel.tsx
- src/components/NetworkSelector.tsx
- src/components/Tab.tsx
- src/components/TezosAccountView.tsx
- src/components/TezosBlockView.tsx
- src/components/TezosDataView.tsx
- src/components/TezosOperationView.tsx
- src/config.tsx
- src/containers.tsx
- src/index.tsx
- src/reducers.tsx
- src/store.ts
- src/style.css
- src/types.tsx
- tsconfig.json
- tslint.json
- webpack.config.js
Resolves GH-28, should be merged after GH-41
> Add linter and prettier

- package.json
- src/components/DataPanel.tsx
- src/components/FilterPanel.tsx
Resolves GH-31, should be merged after GH-41
> Add styled components

- .prettierrc
- .travis.yml
- package-lock.json
- package.json
- src/actions.tsx
- src/components/Arronax.tsx
- src/components/DataPanel.tsx
- src/components/ExpandableGrid.tsx
- src/components/ExpandableGridRow.tsx
- src/components/FilterPanel.tsx
- src/components/NetworkSelector.tsx
- src/components/Tab.tsx
- src/components/TezosAccountView.tsx
- src/components/TezosBlockView.tsx
- src/components/TezosDataView.tsx
- src/components/TezosOperationView.tsx
- src/config.tsx
- src/containers.tsx
- src/index.tsx
- src/reducers.tsx
- src/store.ts
- src/style.css
- src/types.tsx
- tsconfig.json
- tslint.json
- webpack.config.js
`githubToken` should be defined on travis.
App is deployed on github pages.
resolves GH-42, should be merged after GH-41
> [WIP] Add travis config

- src/components/Arronax.tsx
- src/components/FilterPanel.tsx
#56
Also refactored a little FilterPanel component in a way to prevent code duplicates
> 56-add-filters

- package-lock.json
- package.json
- src/components/NetworkSelector.tsx
#55
Upgraded react-script-ts library
> 55-network-switch

- package.json
- public/config.json
- src/components/Arronax.tsx
- src/config.tsx
#78 
If u want to use some different configuration, just change/replace parameters in:
./public/config.json - for dev builds
./build/config.json - for production builds
> Configuration-from-external-file

- src/containers/App/index.tsx
- src/reducers/app/thunks.ts
- src/types/index.ts
> UI updates

- src/components/FilterPanel/style.ts
- src/components/Header/index.tsx
- fixed the searchbox width
- resized the filter value
> Input field sizing

- src/assets/locales/en/translation.json
- src/containers/Entities/operation_template.tsx
> Entity modals

- src/containers/CustomTable/index.tsx
- src/containers/Entities/account_template.tsx
- src/containers/Entities/operation_template.tsx
Use operations data to augment account data
> Cross-entity data enrichment

- src/components/Clipboard/Clipboard-container.tsx
- src/components/Clipboard/Clipboard-styles.tsx
- src/components/Clipboard/Clipboard-types.ts
- src/components/Clipboard/Clipboard-view.tsx
- src/components/Clipboard/index.tsx
- src/containers/Entities/account_template.tsx
- src/containers/Entities/block_template.tsx
- src/containers/Entities/default.tsx
- src/containers/Entities/operation_template.tsx
- src/utils/render.tsx
> Fix/353 Copy content buttons on modals

- src/reducers/app/selectors.ts
- src/reducers/app/thunks.ts
- src/utils/general.ts
> Refresh metadata on network change

- src/containers/App/index.tsx
keep in mind it is not possible to customize the content of the message, due to security reasons, so different browsers will display a pre-designed sentence
> Warn when leaving Arronax #315

- src/containers/App/index.tsx
- src/containers/CustomTable/index.tsx
- src/containers/Entities/account_template.tsx
- src/containers/Entities/block_template.tsx
- src/containers/Entities/default.tsx
- src/containers/Entities/operation_template.tsx
- src/containers/Entities/types.tsx
- src/reducers/app/thunks.ts
- pass correct params
- fix return value warning
- refactor entity modal types
- handle submit query error
> Pass correct params 376

- .prettierrc
- package-lock.json
- package.json
- src/components/FilterPanel/index.tsx
- src/reducers/app/thunks.ts
- src/utils/render.tsx
- display valueMap
- fixed filters border rendering
- update conseiljs
> Display value map

- src/components/Toolbar/styles.tsx
- src/containers/CustomTable/index.tsx
- src/containers/CustomTable/styles.tsx
- src/containers/CustomTable/types.ts
- Fixed table header
- Removed toolbar highlight bar
> Fixed table header 381

- src/components/CustomPaginator/index.tsx
- src/components/Toolbar/styles.tsx
- src/containers/CustomTable/index.tsx
- sync scroll 
- toolbar badge
- paginator width
> Various fixes

- package-lock.json
- src/components/CustomPaginator/index.tsx
- src/components/FilterResults/FilterResults.tsx
- src/components/FilterResults/styles.tsx
- src/components/Tabs/Tabs.tsx
- src/components/Tabs/styles.tsx
- src/components/Tabs/types.tsx
- src/components/Toolbar/styles.tsx
- src/containers/App/index.tsx
- src/containers/App/styles.tsx
- src/containers/App/types.ts
- src/utils/render.tsx
- tab arrows are off
- layout items aligned to 30px
- expand tabs based on route
- filter results entity title
> Aligned layout

- package-lock.json
- package.json
- src/containers/CustomTable/index.tsx
- src/utils/render.tsx
- fixed list filter display
- fixed table scroll
> Display fixes

- package-lock.json
- package.json
- src/components/FilterResults/FilterResults.tsx
- src/components/Footer/index.tsx
- src/components/Tabs/Tabs.tsx
- src/containers/App/index.tsx
- src/containers/App/types.ts
- src/reducers/app/actions.ts
- src/reducers/app/reducers.ts
- src/reducers/app/thunks.ts
- src/reducers/app/types.ts
- src/reducers/index.ts
- src/reducers/modal/actions.ts
- src/reducers/modal/reducers.ts
- src/reducers/modal/selectors.ts
- src/reducers/modal/types.ts
- src/types/index.ts
- src/utils/attributes.ts
refactor data loading behaviour
release tag visibility
tab arrows
close https://github.com/Cryptonomic/Arronax/issues/429 and https://github.com/Cryptonomic/Arronax/issues/404
> Metadata switch on URL navigation

- .dockerignore
- Dockerfile
- README.md
- package-lock.json
- package.json
- src/index.tsx
- update for ConseilJS 5.0.x
- docker config
> Update for ConseilJS 5.0.x

- .travis.yml
- Dockerfile
- README.md
- package-lock.json
- package.json
This PR simplifies the travis config along with other minor changes.
> Project file updates
